
/**
* StringServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringService.idl
* Monday, 4 May, 2026 12:20:43 AM IST
*/

public interface StringServiceOperations 
{
  String reverseString (String str);
  String convertToUppercase (String str);
} // interface StringServiceOperations
