
/**
* StringServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringService.idl
* Monday, 4 May, 2026 12:20:43 AM IST
*/

public final class StringServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public StringService value = null;

  public StringServiceHolder ()
  {
  }

  public StringServiceHolder (StringService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = StringServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    StringServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StringServiceHelper.type ();
  }

}
